### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by 1337Flash** [riv3n/freeChamp#5]
Attempting to loging with a non-existing account throws a ValueError screen.

![](http://puu.sh/ieWqK/c0382cf9bc.png)

**Comment by despertargz** [comment]
yay, our first free champ issue.

**Comment by 1337Flash** [comment]
Glad to be a debugger for this epic project :-P

On Sat, Jun 6, 2015 at 4:26 PM, despertargz <notifications@github.com>
wrote:

> yay, our first free champ issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/riv3n/freeChamp/issues/5#issuecomment-109645733>.
>



-- 
Kyle Muffley
Programmer
Electronic Design & Manufacturing
Website: ElecDM.com <http://www.ElecDM.com>
Email: 1337Flash@gmail.com

**Comment by the-gato** [comment]
attempting to login with non-existent email now shows, "Unauthorized".
